vote/urls.py
# Importing the required modules

# The admin module is used to create the admin site for the application
# using the default django admin site module
from django.contrib import admin

# The path module is used to create the url patterns for the application
# to map the urls to the views
from django.urls import path

# The views module is used to import the views from the views.py file
from voteapp import views

# The settings module is used to import the settings from the settings.py file
# to get the media, static files and other settings
from django.conf import settings

# The static module is used to import the static files from the settings.py file
from django.conf.urls.static import static


# The urlpatterns list is used to store the url patterns for the application
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.homeView, name='home'),
    path('register/', views.registrationView, name='registration'),
    path('login/', views.loginView, name='login'),
    path('dashboard/', views.dashboardView, name='dashboard'),
    path('logout/', views.logoutView, name='logout'),
    path('position/', views.positionView, name='position'),
    path('candidate/<int:pos>/', views.candidateView, name='candidate'),
    path('candidate/detail/<int:id>/', views.candidateDetailView, name='detail'),
    path('result/', views.resultView, name='result'),
    path('changepass/', views.changePasswordView, name='changepass'),
    path('editprofile/', views.editProfileView, name='editprofile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voteapp/models.py
# Importing the required modules

# The models module is used to create the database tables and the fields
from django.db import models

# The User model is used to create the user table using the default django user model
from django.contrib.auth.models import User


# ------------------ Online Voting System - Models ------------------ #

# The Position model is used to create the position table
class Position(models.Model):

    # The title field is used to store the position title
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title

# The Candidate model is used to create the candidate table
class Candidate(models.Model):

    # The name field is used to store the candidate name
    name = models.CharField(max_length=100)

    # The total_vote field is used to store the total number of votes received by the candidate
    total_vote = models.IntegerField(default=0, editable=False)

    # The position field is used to store the position of the candidate
    position = models.ForeignKey(Position, on_delete=models.CASCADE)

    # The image field is used to store the image of the candidate
    image = models.ImageField(verbose_name="Candidate Pic", upload_to='images/')

    def __str__(self):
        return "{} - {}".format(self.name, self.position.title)

# The ControlVote model is used to create the control_vote table
class ControlVote(models.Model):

    # The user field is used to store the user who has voted
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # The position field is used to store the position for which the user has voted
    position = models.ForeignKey(Position, on_delete=models.CASCADE)

    # The status field is used to store the status of the vote
    status = models.BooleanField(default=False)

    def __str__(self):
        return "{} - {} - {}".format(self.user, self.position, self.status)

templates/Password.html
{% extends "base.html" %}
{% block title %}Change Password{% endblock %}
{% block content %}
{% load widget_tweaks %}
<br>
<br>
<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         <h5 class="card-title">Password Change Form</h5>
         <form action="." method="post">
           {% csrf_token %}
           {% for field in form %}
             <div class="form-group">
               {% if field.errors %}
                 {% for error in field.errors %}
                   <ul>
                     <li>{{error}}</li>
                   </ul>
                 {% endfor %}
               {% endif %}
               {{ field.label_tag }}
               {% render_field field class="form-control" %}
               <br>
               {% if field.help_text %}
                 <small class="form-text text-muted">{{field.help_text}}</small>
               {% endif %}
             </div>
           {% endfor %}
           <button type="submit" class="col-md-12 btn btn-primary">Update</button>
         </form>
       </div>
     </div>
   </div>
 </div>
</div>


<style>
 body {
   background: linear-gradient(45deg, #b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }
</style>


{% endblock %}

templates/Position.html
{% extends "base.html" %}
{% block title %} Position {% endblock %}
{% block content %}
<br />
<div class="container-fluid as-full">
 <h1 class="card-title d-flex justify-content-center">
   Available Position For Vote
 </h1>
</div>
<br />
<br />
<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         <table class="table table-striped table-hover">
           <thead>
             <tr>
               <th scope="col">Position</th>
               <th scope="col">Vote</th>
             </tr>
           </thead>
           <tbody>
             {% for candidateID in obj %}
             <tr>
               <td>{{candidateID.title}}</td>
               <td>
                 <a
                   href="{% url 'candidate' candidateID.id %}"
                   class="btn btn-primary btn-sm"
                   >Vote</a
                 >
               </td>
             </tr>
             {% empty %}
             <p>No Positions Available</p>
             {% endfor %}
           </tbody>
         </table>
       </div>
     </div>
   </div>
 </div>
</div>


<style>
 body {
   background: linear-gradient(45deg, #b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }
</style>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
 <head>
   <meta charset="utf-8" />
   <meta
     name="viewport"
     content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />
   <link
     href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
     rel="stylesheet"
     integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
     crossorigin="anonymous"
  />
   <script
     src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
     integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
     crossorigin="anonymous"
   ></script>
   <script
     src="https://kit.fontawesome.com/114f8f7e3d.js"
     crossorigin="anonymous"
   ></script>


   <title>{% block title %}{% endblock %}</title>
 </head>
 <body>
   <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
     <div class="container-fluid">
       <a class="navbar-brand" href="{% url 'home' %}">Online Voting System</a>
       <button
         class="navbar-toggler"
         type="button"
         data-bs-toggle="collapse"
         data-bs-target="#navbarNavAltMarkup"
         aria-controls="navbarNavAltMarkup"
         aria-expanded="false"
         aria-label="Toggle navigation"
       >
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
         <div class="navbar-nav">
           {% if request.user.is_authenticated %}
           <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
           <a class="nav-link" href="{% url 'editprofile' %}">Edit Profile</a>
           <a class="nav-link" href="{% url 'changepass' %}"
             >Change Password</a
           >
           <a class="nav-link" href="{% url 'logout' %}">Logout</a>
           {% else %}
           <a class="nav-link" href="{% url 'login' %}">Login</a>
           <a class="nav-link" href="{% url 'registration' %}">Register</a>
           {% endif %}
         </div>
       </div>
     </div>
   </nav>
   <div class>{% block content %} {% endblock %}</div>
 </body>
</html>

templates/candidate.html
{% extends "base.html" %}
{% block title %}Candidate{% endblock %}
{% block content %}
{% if messages %}
 {% for message in messages %}
   <div class="alert alert-danger" role="alert">{{ message }}</div>
 {% endfor %}
{% endif %}


<br />
<div class="container-fluid as-full">
 <h3 class="card-title d-flex justify-content-center">
   Available Candidates for the Election of
 </h3>
 <h2 class="card-title d-flex justify-content-center">{{ obj.title }}</h2>
</div>


<br />
<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         <form action="" method="POST">
           {% csrf_token %}
           <table class="table table-striped table-hover">
             <thead>
               <tr>
                 <th scope="col">Candidate</th>
                 <th scope="col">Vote</th>
               </tr>
             </thead>
             <tbody>
               {% for candidateID in obj.candidate_set.all %}
               <tr>
                 <td>
                   <a href="{% url 'detail' candidateID.id %}">{{candidateID.name}}</a>
                 </td>
                 <td>
                   <input
                     type="radio"
                     id="id_{{candidateID.id}}"
                     name="{{candidateID.position}}"
                     value="{{candidateID.id}}"
                     class="custom-control-input"
                     required
                  />
                 </td>
               </tr>
               {% empty %}
                 <p>No Candidates Available</p>
               {% endfor %}
             </tbody>
           </table>
           <input
             type="submit"
             class="col-md-12 btn btn-primary"
             value="Vote"
          />
         </form>
       </div>
     </div>
   </div>
 </div>
</div>


<br />
<br />
<br />
<br />
<br />


<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         <a href="{% url 'position' %}" class="col-md-12 btn btn-primary">Go Back</a>
       </div>
     </div>
   </div>
 </div>
</div>


<style>
 body {
   background: linear-gradient(45deg, #b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }
</style>


{% endblock %}

templates/candidate_detail.html
{% extends "base.html" %}
{% block title %}Candidate Details{% endblock %}
{% block content %}
<br>
<div class="container-fluid as-full">
 <div class="row as-flex d-flex justify-content-center">
   <div class="col-5 align-self-center" >
     <div class="card border-primary mb-3 bg-dark" style="width: 25rem;">
       <div class="card-body">
         <div class="card border-primary mb-3 bg-light" style="width: 23rem;">
           <img src="{{ obj.image.url }}" class="card-img-top" alt="Candidate Image">
           <div class="card-body">
             <table class="table table-striped table-hover">
               <tbody>
                 <tr>
                   <td><b>Name </b></td>
                   <td>{{ obj.name }}</td>
                 </tr>
                 <tr>
                   <td><b>Competing For</b></td>
                   <td>{{ obj.position }}</td>
                 </tr>
               </tbody>
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>


<style>
 body{
   background: linear-gradient(45deg,#b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }
</style>


{% endblock %}

templates/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<br>
<h1 class="text-center">Welcome to Online Voting System</h1>
<h2 class="text-center">Hi, {{request.user.get_full_name }}</h2>
<section class="hero-section">
 <div class="card-grid">
   <a class="card  d-flex" href="{% url 'position' %}">
     <div class="card__background" style="background-image: url(https://img.freepik.com/free-vector/realistic-vector-icon-ballot-box-made-glass-hand-putting-voting-paper-inside-election-conce_134830-1493.jpg?w=2000)"></div>
     <div class="card__content">
       <p class="card__category">Vote</p>
       <h3 class="card__heading">Click Here To Vote</h3>
     </div>
   </a>
   <a class="card" href="{% url 'result' %}">
     <div class="card__background" style="background-image: url(https://media.istockphoto.com/id/1281075008/vector/success.jpg?s=612x612&w=0&k=20&c=79U0bXwmDlMwkBQ_qyzGItiRtItpXIQJsSKc2UlvQkk=)"></div>
     <div class="card__content">
       <p class="card__category">Result</p>
       <h3 class="card__heading">Click Here To See Result</h3>
     </div>
   </a>
 <div>
</section>


<style>
 :root{
   --background-dark: #2d3548;
   --text-light: rgba(231, 231, 231, 0.9);
   --text-lighter: rgba(255, 255, 255, 0.9);
   --spacing-s: 8px;
   --spacing-m: 16px;
   --spacing-l: 24px;
   --spacing-xl: 32px;
   --spacing-xxl: 64px;
   --width-container: 1200px;
 }
  *{
   border: 0;
   margin: 0;
   padding: 0;
   box-sizing: border-box;
 }
  html{
   height: 100%;
   font-family: 'Montserrat', sans-serif;
   font-size: 14px;
 }
  body{
   height: 100%;
   background: linear-gradient(45deg,#b57bee, #00e3fd);
 }
  .hero-section{
   align-items: flex-start;
   display: flex;
   min-height: 100%;
   justify-content: center;
   padding: var(--spacing-xxl) var(--spacing-l);
 }
  .card-grid{
   display: grid;
   grid-template-columns: repeat(1, 1fr);
   grid-column-gap: var(--spacing-l);
   grid-row-gap: var(--spacing-l);
   max-width: var(--width-container);
   width: 50%;
 }
  @media(min-width: 540px){
   .card-grid{
     grid-template-columns: repeat(2, 1fr);
   }
 }
  @media(min-width: 960px){
   .card-grid{
     grid-template-columns: repeat(2, 1fr);
   }
 }
  .card{
   list-style: none;
   position: relative;
   border-radius: var(--spacing-l);
 }
  .card:before{
   content: '';
   display: block;
   padding-bottom: 150%;
   width: 100%;
 }
  .card__background{
   background-size: cover;
   background-position: center;
   border-radius: var(--spacing-l);
   bottom: 0;
   filter: brightness(0.60) saturate(1.2) contrast(0.85);
   left: 0;
   position: absolute;
   right: 0;
   top: 0;
   transform-origin: center;
   transform: scale(1) translateZ(0);
   transition:
     filter 200ms linear,
     transform 200ms linear;
 }
  .card:hover .card__background{
   transform: scale(1.05) translateZ(0);
 }
  .card-grid:hover > .card:not(:hover) .card__background{
   filter: brightness(0.5) saturate(0) contrast(1.2) blur(20px);
 }
  .card__content{
   left: 0;
   padding: var(--spacing-l);
   position: absolute;
   top: 0;
 }
  .card__category{
   color: var(--text-light);
   font-size: 0.9rem;
   margin-bottom: var(--spacing-s);
   text-transform: uppercase;
 }
  .card__heading{
   color: var(--text-lighter);
   font-size: 1.9rem;
   text-shadow: 2px 2px 20px rgba(0,0,0,0.2);
   line-height: 1.4;
   word-spacing: 100vw;
 }
</style>


{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}
{% block title %}Update Profile{% endblock %}
{% block content %}
{% load widget_tweaks %}


<br>
<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         {% if note %}
         <h3 class="text text-muted">{{note}}</h3>
         {% endif %}
         <h5 class="card-title d-flex justify-content-center"> Update Profile</h5>
         <form action="" method="POST">
           {% csrf_token %}
             {% for field in form %}
             <div class="form-group">
               {% if field.errors %}
                 {% for error in field.errors %}
                   <ul>
                     <li>{{error}}</li>
                   </ul>
                 {% endfor %}
               {% endif %}
               {{ field.label_tag }}
               {% render_field field class="form-control" %}
               {% if field.help_text %}
               <small class="form-text text-muted">{{field.help_text}}</small>
               <br>
                 {% endif %}
               <br>
             </div>
           {% endfor %}
           <button type="submit" class="col-md-12 btn btn-primary">Update</button>
       </div>
     </div>
   </div>
 </div>
</div>


<style>
 body {
   background: linear-gradient(45deg, #b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }
</style>


{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}Online Voting System{%endblock%}
{% block content %}
<br>
<div class="jumbotron">
 {% if messages %} {% for message in messages %}
 <div class="alert alert-success" role="alert">{{ message }}</div>
 {% endfor %} {% endif %}
 <h1 class="display-4 d-flex justify-content-center">
   Welcome to Online Voting System
 </h1>
 <hr class="my-4 bg-dark d-flex justify-content-center" style="height: 2px" />
 <div class="d-flex justify-content-center">
   <img
     src="https://www.theheraldtimes.com/wp-content/uploads/2018/05/kisspng-ballot-box-voting-election-clip-art-voting-box-png-file-5aa1fb83b479c1.8490900715205651237392.png"
     alt="Ballot Box"
     width="300"
     height="300"
  />
 </div>


 <hr class="my-5 bg-dark d-flex justify-content-center" style="height: 2px" />


 <p class="lead d-flex justify-content-center">
   This is a simple voting system where you can vote for your favourite
   candidate.
 </p>
 <p class="lead d-flex justify-content-center">
   Admin can add candidates and post the election.
 </p>
 <p class="lead d-flex justify-content-center">
   User can vote for the candidates.
 </p>
</div>


<style>
 body {
   background: linear-gradient(45deg, #6ef195, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }
</style>


{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}


<br>
<br>
<br>
<br>
<br>
<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         {% if messages %}
           {% for message in messages %}
             <div class="alert alert-danger d-flex justify-content-center" role="alert">
               {{ message }}
             </div>
           {% endfor %}
         {% endif %}
         <h5 class="card-title d-flex justify-content-center">User Login</h5>
         <form action="." method="POST">
           {% csrf_token %}
             <div class="form-group">
               <label for="id_username">Username:</label>
               <input type="text" name="username" class="form-control" id="id_username" required><i
                 class="iconinput fa fa-user"></i>
             </div>
             <div class="form-group">
               <label for="id_password">Password:</label>
               <input type="password" name="password" class="form-control" id="id_password" required><i
                 class="iconinput fa fa-keyboard"></i>
             </div>
           <button type="submit" class="col-md-12 btn btn-primary">Login</button>
         </form>
       </div>
     </div>
   </div>
 </div>
</div>




<style>
 body {
   background: linear-gradient(45deg, #b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }


 .as-full {
   width: 100%;
   height: 100%;
 }


 .form-control {
   padding-left: 30px;
   padding-right: 30px;
 }


 .iconinput {
   position: relative;
   z-index: 1;
   left: 10px;
   top: -31px;
   width: 0;
 }
</style>


{% endblock %}

templates/registration.html
{% extends "base.html" %}
{% block title %}Registration{% endblock %}
{% block content %}
{% load widget_tweaks %}
<br />
<br />
<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         {% if note %}
         <h3 class="text text-muted">{{note}}</h3>
         {% endif %}
         <h5 class="card-title">User Registration</h5>
         <form action="" method="POST">
           {% csrf_token %}
           {% for field in form %}
             <div class="form-group">
               {% if field.errors %}
                 {% for error in field.errors %}
                   <ul>
                     <li>{{error}}</li>
                   </ul>
                 {% endfor %}
               {% endif %}
                 {{ field.label_tag }}
                 {% render_field field class="form-control" %}
               {% if field.help_text %}
               <small class="form-text text-muted">{{field.help_text}}</small>
               {% endif %}
             </div>
             <br>
           {% endfor %}
           <button type="submit" class="col-md-12 btn btn-primary">Login</button>
         </form>
       </div>
     </div>
   </div>
 </div>
</div>


<style>
 body {
   background: linear-gradient(45deg, #b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }


 .as-full {
   width: 100%;
   height: 100%;
 }


 .form-control {
   padding-left: 30px;
   padding-right: 30px;
 }
</style>


{% endblock %}

templates/result.html
{% extends "base.html" %}
{% block title %}Result Page{% endblock %}
{%block content %}
<h2 class="text-center">Result</h2>
<div class="container-fluid as-full">
 <div class="row as-full d-flex justify-content-center">
   <div class="col-5 align-self-center">
     <div class="card">
       <div class="card-body">
         <table class="table table-striped table-hover">
           <thead>
             <tr>
               <th scope="col">Candidate Name</th>
               <th scope="col">Candidate Position</th>
               <th scope="col">Total Vote</th>
             </tr>
           </thead>
           <tbody>
             {% for i in obj %}
             <tr>
               <td>{{ i.name }}</td>
               <td>{{ i.position }}</td>
               <td>{{ i.total_vote }}</td>
             </tr>
             {% endfor %}
           </tbody>
         </table>
       </div>
     </div>
   </div>
 </div>
</div>


<style>
 body {
   background: linear-gradient(45deg, #b57bee, #00e3fd);
   background-repeat: no-repeat;
   background-attachment: fixed;
   background-size: cover;
 }
</style>


{% endblock %}